// defaults.ts — default (empty) values for every field in StructuredFormData.
//
// Passed to React Hook Form's `defaultValues` in PCRForm so the form initializes
// in a clean state, and also used by the "New Call — Clear All Fields" reset.
// Every field is an empty string so TypeScript is satisfied without null checks.

import { StructuredFormData } from "@/lib/types";

export const DEFAULT_FORM_VALUES: StructuredFormData = {
  ambulanceNumber: "",
  transportType: "",
  sceneLocation: "",
  sceneLocationCustom: "",
  sceneHospitalSystem: "",
  sceneHospitalName: "",
  sceneHospitalCampus: "",
  sceneHospitalCustom: "",
  sceneFloorRoom: "",
  destination: "",
  destinationCustom: "",
  destinationHospitalSystem: "",
  destinationHospitalName: "",
  destinationHospitalCampus: "",
  destinationHospitalCustom: "",
  destinationRoom: "",
  reportReceivedFrom: "",
  patientAge: "",
  patientDOB: "",
  patientAddress: "",
  patientGender: "",
  chiefComplaint: "",
  transportReason: "",
  transportReasonCustom: "",
  oxygenDelivery: "",
  oxygenLiters: "",
  castType: "",
  sectionType: "",
  mentalStatus: "",
  medicalHistory: "",
  airway: "",
  breathing: "",
  circulation: "",
  skin: "",
  skinCustom: "",
  bloodPressure: "",
  bloodPressureNote: "",
  heartRate: "",
  heartRateNote: "",
  spo2: "",
  spo2Note: "",
  painScore: "",
  patientHeight: "",
  patientWeight: "",
  patientComplaints: "",
  mobilityLevel: "",
  transferType: "",
  transportPosition: "",
  transportPositionCustom: "",
  additionalInfo: "",
};
