// diagnoses.ts — master list of medical diagnoses for the MedHistory autocomplete.
//
// Each entry has a `full` name (displayed in the dropdown and used as the tag label)
// and an `abbr` abbreviation (shown as a hint and also searchable).
// The MedHistory component filters this list against the user's typed input,
// matching on either the full name or abbreviation.

export type Diagnosis = { full: string; abbr: string };

export const DIAGNOSES: Diagnosis[] = [
  { full: "Alzheimer's disease", abbr: "Alzheimer's dz" },
  { full: "Anemia", abbr: "Anemia" },
  { full: "Angina", abbr: "Angina" },
  { full: "Anxiety", abbr: "Anxiety" },
  { full: "Aphasia", abbr: "Aphasia" },
  { full: "Asthma", abbr: "Asthma" },
  { full: "Atrial fibrillation", abbr: "A-fib" },
  { full: "Bipolar disorder", abbr: "Bipolar d/o" },
  { full: "Bladder disorder", abbr: "Bladder d/o" },
  { full: "Cancer", abbr: "CA" },
  { full: "Cardiomyopathy", abbr: "Cardiomyopathy" },
  { full: "Chronic kidney disease", abbr: "CKD" },
  { full: "Chronic obstructive pulmonary disease", abbr: "COPD" },
  { full: "Congestive heart failure", abbr: "CHF" },
  { full: "Constipation", abbr: "Constipation" },
  { full: "Coronavirus disease 2019", abbr: "COVID-19" },
  { full: "Coronary artery disease", abbr: "CAD" },
  { full: "Crohn's disease", abbr: "Crohn's dz" },
  { full: "Dementia", abbr: "Dementia" },
  { full: "Depression", abbr: "Depression" },
  { full: "Type 1 Diabetes", abbr: "T1D" },
  { full: "Type 2 Diabetes", abbr: "T2D" },
  { full: "Dysphasia", abbr: "Dysphasia" },
  { full: "End-stage renal disease", abbr: "ESRD" },
  { full: "Esophagitis", abbr: "Esophagitis" },
  { full: "Fecal impaction", abbr: "Fecal impaction" },
  { full: "Gastritis", abbr: "Gastritis" },
  { full: "Gastroesophageal reflux disease", abbr: "GERD" },
  { full: "Glaucoma", abbr: "Glaucoma" },
  { full: "Heart failure", abbr: "HF" },
  { full: "Hearing loss", abbr: "Hearing loss" },
  { full: "Hemiparesis", abbr: "Hemiparesis" },
  { full: "Hemiplegia", abbr: "Hemiplegia" },
  { full: "Hepatitis", abbr: "Hepatitis" },
  { full: "Human immunodeficiency virus infection", abbr: "HIV" },
  { full: "Hyperlipidemia", abbr: "HLD" },
  { full: "Hypertension", abbr: "HTN" },
  { full: "Hypothyroidism", abbr: "Hypothyroidism" },
  { full: "Intracranial hemorrhage", abbr: "ICH" },
  { full: "Irritable bowel syndrome", abbr: "IBS" },
  { full: "Liver disease", abbr: "Liver dz" },
  { full: "Obstructive sleep apnea", abbr: "OSA" },
  { full: "Osteomyelitis", abbr: "Osteomyelitis" },
  { full: "Overactive bladder", abbr: "OAB" },
  { full: "Paraplegia", abbr: "Paraplegia" },
  { full: "Parkinson's disease", abbr: "Parkinson's dz" },
  { full: "Peptic ulcer disease", abbr: "PUD" },
  { full: "Pneumonia", abbr: "PNA" },
  { full: "Polio", abbr: "Polio" },
  { full: "Post-traumatic stress disorder", abbr: "PTSD" },
  { full: "Prior heart attack", abbr: "Prior MI" },
  { full: "Pulmonary hypertension", abbr: "Pulm HTN" },
  { full: "Quadriplegia", abbr: "Quadriplegia" },
  { full: "Radiculopathy", abbr: "Radiculopathy" },
  { full: "Respiratory syncytial virus infection", abbr: "RSV" },
  { full: "Sciatica", abbr: "Sciatica" },
  { full: "Seizure disorder", abbr: "Seizure d/o" },
  { full: "Sepsis", abbr: "Sepsis" },
  { full: "Sleep apnea", abbr: "OSA" },
  { full: "Spinal stenosis", abbr: "Spinal stenosis" },
  { full: "Stroke", abbr: "CVA" },
  { full: "Substance use disorder", abbr: "SUD" },
  { full: "Supraventricular tachycardia", abbr: "SVT" },
  { full: "Thrombocytopenia", abbr: "Thrombocytopenia" },
  { full: "Tuberculosis", abbr: "TB" },
  { full: "Ulcerative colitis", abbr: "UC" },
  { full: "Valvular heart disease", abbr: "Valvular heart dz" },
  { full: "Ventricular tachycardia", abbr: "VT" },
  { full: "Blindness", abbr: "Blindness" },
  { full: "Multiple Sclerosis", abbr: "MS" },
  { full: "Persistent Postural-Perceptual Dizziness", abbr: "PPPD" },
  { full: "Orthostatic Hypotension", abbr: "OH" },
  { full: "Benign Prostatic Hyperplasia", abbr: "BPH" },
];
